### ISSUE TITLE
 preparation failed

### ISSUE THREAD

**Issue by Beast12** [marcfager/nspanel-mf#35]
[nspanel.zip](https://github.com/marcfager/nspanel-mf/files/14472407/nspanel.zip)
Verify Installation is ok, only when I try to install the ESPHome I get this:
![image](https://github.com/marcfager/nspanel-mf/assets/5346327/ea4c9e5c-c179-47d8-96b5-8accfc6156fa)
What went wrong:
``
INFO ESPHome 2024.2.1
INFO Reading configuration /config/esphome/nspanelbroosbedroom.yaml...
INFO Detected timezone 'Europe/Brussels'
INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1041, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1028, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 407, in command_compile
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 192, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 204, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 679, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 184, in wrapped
    await coro(conf)
  File "/data/external_components/b5254113/esphome/components/nextion/display.py", line 92, in to_code
    await display.register_display(var, config)
  File "/esphome/esphome/components/display/__init__.py", line 119, in register_display
    await cg.register_component(var, config)
  File "/esphome/esphome/cpp_helpers.py", line 56, in register_component
    raise ValueError(
ValueError: Component ID disp1 was not declared to inherit from Component, or was registered twice. Please create a bug report with your configuration.
``
The NSpanel config is added as a zip

**Comment by kamilkara** [comment]
same issue!

![image](https://github.com/user-attachments/assets/24d697d8-c778-44cb-b20f-1aff1cba7630)

![image](https://github.com/user-attachments/assets/139e99c2-6851-4631-a3c5-44525aa033b2)
